import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
  icons: {
    icon: '/SpCoin/images/avatar.png', // ✅ public path only
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div>{children}</div>
}
