import SpCoinWrapper from '@/components/Wrappers/SpCoinWrapper'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'spCoin',
    description: 'Generated by create next app',
    icons: {
      icon: 'http://localhost:3000/SpCoin/avatar.png',
    },
  }
  
export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <div>
            {children}
        </div>
    )
}
