import type { Metadata } from 'next'
import { AppWrapper } from './Context'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
    <html lang="en">
        {/* <AppWrapper> */}
            {children}
        {/* </AppWrapper> */}
    </html>
    )
}
