import { ExchangeWrapper } from '@/context'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
    <>
        <ExchangeWrapper>
            {children}
        </ExchangeWrapper>
    </>
    )
}
