import type { Metadata } from 'next'
import { ExchangeWrapper } from '../lib/context'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
    <>
        {/* <ExchangeWrapper> */}
            {children}
        {/* </ExchangeWrapper> */}
    </>
    )
}
