// File: lib/structure/constants/enums/spCoinDisplay.ts
export enum SP_COIN_DISPLAY {
  TRADING_STATION_PANEL,
  SELL_SELECT_SCROLL_PANEL,
  BUY_SELECT_SCROLL_PANEL,
  RECIPIENT_SELECT_CONFIG_PANEL,
  AGENT_SELECT_CONFIG_PANEL,
  ERROR_MESSAGE_PANEL,
  SPONSOR_RATE_CONFIG_PANEL,
  UNDEFINED, // never persist
}
