// File: lib/structure/constants/enums/spCoinDisplay.ts

export enum SP_COIN_DISPLAY {
  AGENT_SELECT_PANEL,
  BUY_SELECT_SCROLL_PANEL,
  ERROR_MESSAGE_PANEL,
  RECIPIENT_SELECT_PANEL,
  SELL_SELECT_SCROLL_PANEL,
  SPONSOR_RATE_CONFIG_PANEL,
  TRADING_STATION_PANEL,
  UNDEFINED,
}
