// File: lib/structure/constants/enums/spCoinDisplay.ts

export enum SP_COIN_DISPLAY_NEW {
  UNDEFINED = 0,
  TRADING_STATION_PANEL = 1,
  SELL_SELECT_SCROLL_PANEL = 2,
  BUY_SELECT_SCROLL_PANEL = 3,
  RECIPIENT_SELECT_SCROLL_PANEL = 4,
  AGENT_SELECT_SCROLL_PANEL = 5,
  SPONSOR_RATE_CONFIG_PANEL = 6,
  ERROR_MESSAGE_PANEL = 7,
}
