import SpCoinWrapper from '@/app/components/SpCoinWrapper'
import type { Metadata } from 'next'
import Header from '../../components/panes/header'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <div>
            {children}
        </div>
    )
}
