import ConnectWrapper2 from '@/app/components/ConnectWrapper2'
import { C } from 'msw/lib/glossary-de6278a9'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <div>
            {/* <ConnectWrapper2> */}
            {children}
            {/* </ConnectWrapper2> */}
        </div>
    )
}
