// File: app/(menu)/(dynamic)/SponsorCoinLab/methods/shared/spCoinAbi.ts
export const SPCOIN_LAB_ABI = [
  'function getSerializedSPCoinHeader() view returns (string)',
  'function getAccountList() view returns (address[])',
  'function getSerializedAccountRecord(address _accountKey) view returns (string)',
  'function getSerializedAccountRewards(address _accountKey) view returns (string)',
  'function getRewardAccounts(address _accountKey, uint256 _rewardType) view returns (string)',
  'function getRecipientRateList(address _sponsorKey, address _recipientKey) view returns (uint256[])',
  'function getRecipientRateAgentList(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey) view returns (address[])',
  'function getAgentRateList(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey, address _agentKey) view returns (uint256[])',
  'function getAgentTotalRecipient(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey, address _agentKey) view returns (uint256)',
  'function getSerializedRateTransactionList(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey, address _agentKey, uint256 _agentRateKey) view returns (string)',
  'function getRecipientRateTransactionList(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey) view returns (string)',
  'function getSerializedRecipientRateList(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey) view returns (string)',
  'function getSerializedRecipientRecordList(address _sponsorKey, address _recipientKey) view returns (string)',
  'function serializeAgentRateRecordStr(address _sponsorKey, address _recipientKey, uint256 _recipientRateKey, address _agentKey, uint256 _agentRateKey) view returns (string)',
  'function testStakingRewards(uint256 lastUpdateTime, uint256 testUpdateTime, uint256 interestRate, uint256 quantity) view returns (uint256)',
  'function getStakingRewards(uint256 lastUpdateTime, uint256 interestRate, uint256 quantity) view returns (uint256)',
  'function getTimeMultiplier(uint256 _timeRateMultiplier) view returns (uint256)',
  'function getAccountTimeInSecondeSinceUpdate(uint256 _tokenLastUpdate) view returns (uint256)',
  'function getMillenniumTimeIntervalDivisor(uint256 _timeInSeconds) view returns (uint256)',
  'function addAccountRecord(address _accountKey)',
  'function addRecipient(address _recipientKey)',
  'function addAgent(address _recipientKey, uint256 _recipientRateKey, address _agentKey)',
  'function addSponsorship(address _recipientKey, uint256 _recipientRateKey, address _agentKey, uint256 _agentRateKey, string _strWholeAmount, string _strDecimalAmount)',
  'function addBackDatedSponsorship(address _recipientKey, uint256 _recipientRateKey, address _agentKey, uint256 _agentRateKey, string _strWholeAmount, string _strDecimalAmount, uint256 _transactionTimeStamp)',
  'function unSponsorRecipient(address _recipientKey)',
  'function deleteAccountRecord(address _accountKey)',
  'function updateAccountStakingRewards(address _sourceKey)',
  'function depositStakingRewards(uint256 _accountType, address _sponsorKey, address _recipientKey, uint256 _recipientRate, address _agentKey, uint256 _agentRate, uint256 _amount) returns (uint256)',
  'function transfer(address _to, uint256 _value) returns (bool)',
  'function approve(address _spender, uint256 _value) returns (bool)',
  'function transferFrom(address _from, address _to, uint256 _value) returns (bool)',
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address _owner) view returns (uint256)',
  'function allowance(address _owner, address _spender) view returns (uint256)',
] as const;
