// File: @/lib/structure/exchangeContext/enums/spCoinDisplay.ts

/**
 * IMPORTANT:
 * - This enum is persisted/serialized in multiple places (panel tree, visibility maps, etc).
 * - Do NOT reorder existing members. Add new members at the end (append-only).
 */
export enum SP_COIN_DISPLAY {
  ADD_SPONSORSHIP_BUTTON,
  ADD_SPONSORSHIP_PANEL,
  AFFILIATE_FEE,
  BUY_LIST_SELECT_PANEL,
  BUY_SELECT_PANEL,
  CONFIG_SLIPPAGE_PANEL,
  CONFIG_SPONSORSHIP_PANEL,
  CONNECT_TRADE_BUTTON,
  ERROR_MESSAGE_PANEL,
  EXCHANGE_TRADING_PAIR,
  FEE_DISCLOSURE,
  MAIN_TRADING_PANEL,

  // Detail overlays
  AGENT_ACCOUNT_PANEL,
  RECIPIENT_ACCOUNT_PANEL,
  SPONSOR_ACCOUNT_PANEL,

  // Manage / hub
  MANAGE_PENDING_REWARDS,
  MANAGE_SPONSORSHIPS_BUTTON,

  // Sponsor list select sub-panels (modes)
  UNSPONSOR_SP_COINS,
  CLAIM_PENDING_SPONSOR_COINS,
  CLAIM_PENDING_RECIPIENT_COINS,
  CLAIM_PENDING_AGENT_COINS,

  // Manage overlay
  MANAGE_SPONSORSHIPS_PANEL,

  // Trading list overlays
  SELL_LIST_SELECT_PANEL,
  SELL_SELECT_PANEL,
  TOKEN_CONTRACT_PANEL, // never persist
  STAKING_SPCOINS_PANEL,
  SWAP_ARROW_BUTTON,
  TRADE_CONTAINER_HEADER,
  TRADING_STATION_PANEL,
  UNDEFINED,
  UNSTAKING_SPCOINS_PANEL,

  // First-class list overlays (new)
  ACCOUNT_LIST_REWARDS_PANEL,
  AGENTS,
  RECIPIENTS,
  SPONSORS,

  // Legacy list overlays (migration)
  AGENT_LIST_SELECT_PANEL_OLD,
  RECIPIENT_LIST_SELECT_PANEL_OLD,
}
