// File: lib/structure/exchangeContext/enums/spCoinDisplay.ts

export enum SP_COIN_DISPLAY {
  ADD_SPONSORSHIP_BUTTON,
  ADD_SPONSORSHIP_PANEL,
  AFFILIATE_FEE,
  AGENT_LIST_SELECT_PANEL,
  BUY_LIST_SELECT_PANEL,
  BUY_SELECT_PANEL,
  CLAIM_SPONSOR_REWARDS_LIST_PANEL,
  CONFIG_SLIPPAGE_PANEL,
  CONFIG_SPONSORSHIP_PANEL,
  CONNECT_PRICE_BUTTON,
  ERROR_MESSAGE_PANEL,
  FEE_DISCLOSURE,
  MAIN_TRADING_PANEL,
  MANAGE_AGENT_PANEL,
  MANAGE_AGENTS_PANEL,
  MANAGE_PENDING_REWARDS,
  MANAGE_RECIPIENT_PANEL,
  MANAGE_RECIPIENTS_PANEL,
  MANAGE_SPONSOR_PANEL,
  MANAGE_SPONSORSHIPS_BUTTON,
  MANAGE_SPONSORSHIPS,
  MANAGE_SPONSORSHIPS_PANEL,
  RECIPIENT_LIST_SELECT_PANEL,
  SELL_LIST_SELECT_PANEL,
  SELL_SELECT_PANEL,
  SPONSOR_LIST_SELECT_PANEL, // never persist
  STAKING_SPCOINS_PANEL,
  SWAP_ARROW_BUTTON,
  TRADE_CONTAINER_HEADER,
  TRADING_STATION_PANEL,
  UNDEFINED,
  UNSTAKING_SPCOINS_PANEL,
}

/**
 * Action-model groups (explicit, readable).
 * These DO NOT replace panelRegistry (structure) yet.
 */

export const MAIN_OVERLAY_GROUP = [
  SP_COIN_DISPLAY.TRADING_STATION_PANEL,
  SP_COIN_DISPLAY.BUY_LIST_SELECT_PANEL,
  SP_COIN_DISPLAY.SELL_LIST_SELECT_PANEL,
  SP_COIN_DISPLAY.RECIPIENT_LIST_SELECT_PANEL,
  SP_COIN_DISPLAY.AGENT_LIST_SELECT_PANEL,
  SP_COIN_DISPLAY.ERROR_MESSAGE_PANEL,
  SP_COIN_DISPLAY.MANAGE_SPONSORSHIPS,
  SP_COIN_DISPLAY.SPONSOR_LIST_SELECT_PANEL,
] as const satisfies readonly SP_COIN_DISPLAY[];

export const MANAGE_SCOPED = [
  SP_COIN_DISPLAY.MANAGE_SPONSORSHIPS_PANEL,
  SP_COIN_DISPLAY.UNSTAKING_SPCOINS_PANEL,
  SP_COIN_DISPLAY.STAKING_SPCOINS_PANEL,
  SP_COIN_DISPLAY.MANAGE_RECIPIENTS_PANEL,
  SP_COIN_DISPLAY.MANAGE_AGENTS_PANEL,
  SP_COIN_DISPLAY.CLAIM_SPONSOR_REWARDS_LIST_PANEL,
  SP_COIN_DISPLAY.MANAGE_AGENT_PANEL,
  SP_COIN_DISPLAY.MANAGE_RECIPIENT_PANEL,
] as const satisfies readonly SP_COIN_DISPLAY[];

export const STACK_COMPONENTS = [
  ...MAIN_OVERLAY_GROUP,
  ...MANAGE_SCOPED,
] as const satisfies readonly SP_COIN_DISPLAY[];

/** Fast membership checks (action-model helpers). */
export const IS_MAIN_OVERLAY = new Set<number>(MAIN_OVERLAY_GROUP.map(Number));
export const IS_MANAGE_SCOPED = new Set<number>(MANAGE_SCOPED.map(Number));
export const IS_STACK_COMPONENT = new Set<number>(STACK_COMPONENTS.map(Number));
