// File: @/lib/structure/exchangeContext/enums/spCoinDisplay.ts

/**
 * IMPORTANT:
 * - This enum is persisted/serialized in multiple places (panel tree, visibility maps, etc).
 * - Do NOT reorder existing members. Add new members at the end (append-only).
 */
export enum SP_COIN_DISPLAY {
  ADD_SPONSORSHIP_BUTTON,
  ADD_SPONSORSHIP_PANEL,
  AFFILIATE_FEE,
  BUY_LIST_SELECT_PANEL,
  BUY_SELECT_PANEL,
  CONFIG_SLIPPAGE_PANEL,
  CONFIG_SPONSORSHIP_PANEL,
  CONNECT_TRADE_BUTTON,
  ERROR_MESSAGE_PANEL,
  EXCHANGE_TRADING_PAIR,
  FEE_DISCLOSURE,
  MAIN_TRADING_PANEL,

  // Manage / hub
  MANAGE_PENDING_REWARDS,
  MANAGE_SPONSORSHIPS_BUTTON,

  // Sponsor list select sub-panels (modes)
  ACTIVE_SPONSORSHIPS,
  PENDING_SPONSOR_REWARDS,
  PENDING_RECIPIENT_REWARDS,
  PENDING_AGENT_REWARDS,

  SPONSOR_ACCOUNT,
  RECIPIENT_ACCOUNT,
  AGENT_ACCOUNT,

  // Manage overlay
  MANAGE_SPONSORSHIPS_PANEL,

  // Trading list overlays
  TOKEN_LIST_SELECT_PANEL,
  SELL_SELECT_PANEL,
  TOKEN_PANEL, // never persist (container only)
  STAKING_SPCOINS_PANEL,
  SWAP_ARROW_BUTTON,
  TRADE_CONTAINER_HEADER,
  TRADING_STATION_PANEL,
  UNDEFINED,

  CHEVRON_DOWN_OPEN_PENDING,

  // First-class list overlays (new)
  ACCOUNT_LIST_REWARDS_PANEL,

  // Legacy list overlays (migration)
  AGENT_LIST_SELECT_PANEL,
  RECIPIENT_LIST_SELECT_PANEL,

  // Token / account overlays
  ACCOUNT_PANEL,

  // ✅ NEW: TOKEN_PANEL children (append-only)
  BUY_CONTRACT,
  SELL_CONTRACT,
  PREVIEW_CONTRACT,

  // ✅ NEW: ACCOUNT_LIST_SELECT_PANEL + children (append-only)
  ACCOUNT_LIST_SELECT_PANEL,
  SPONSOR_LIST,
  RECIPIENT_LIST,
  AGENT_LIST,

  // ✅ NEW: staking sub-panel (append-only)
  STAKE_TRADING_SPCOINS_PANEL,
}

/**
 * Canonical DOM-id token for each display enum.
 * Use these ids for UI roots controlled by a specific SP_COIN_DISPLAY state.
 */
export const SP_COIN_DISPLAY_IDS: Record<SP_COIN_DISPLAY, string> = {
  [SP_COIN_DISPLAY.ADD_SPONSORSHIP_BUTTON]: 'ADD_SPONSORSHIP_BUTTON',
  [SP_COIN_DISPLAY.ADD_SPONSORSHIP_PANEL]: 'ADD_SPONSORSHIP_PANEL',
  [SP_COIN_DISPLAY.AFFILIATE_FEE]: 'AFFILIATE_FEE',
  [SP_COIN_DISPLAY.BUY_LIST_SELECT_PANEL]: 'BUY_LIST_SELECT_PANEL',
  [SP_COIN_DISPLAY.BUY_SELECT_PANEL]: 'BUY_SELECT_PANEL',
  [SP_COIN_DISPLAY.CONFIG_SLIPPAGE_PANEL]: 'CONFIG_SLIPPAGE_PANEL',
  [SP_COIN_DISPLAY.CONFIG_SPONSORSHIP_PANEL]: 'CONFIG_SPONSORSHIP_PANEL',
  [SP_COIN_DISPLAY.CONNECT_TRADE_BUTTON]: 'CONNECT_TRADE_BUTTON',
  [SP_COIN_DISPLAY.ERROR_MESSAGE_PANEL]: 'ERROR_MESSAGE_PANEL',
  [SP_COIN_DISPLAY.EXCHANGE_TRADING_PAIR]: 'EXCHANGE_TRADING_PAIR',
  [SP_COIN_DISPLAY.FEE_DISCLOSURE]: 'FEE_DISCLOSURE',
  [SP_COIN_DISPLAY.MAIN_TRADING_PANEL]: 'MAIN_TRADING_PANEL',
  [SP_COIN_DISPLAY.MANAGE_PENDING_REWARDS]: 'MANAGE_PENDING_REWARDS',
  [SP_COIN_DISPLAY.MANAGE_SPONSORSHIPS_BUTTON]: 'MANAGE_SPONSORSHIPS_BUTTON',
  [SP_COIN_DISPLAY.ACTIVE_SPONSORSHIPS]: 'ACTIVE_SPONSORSHIPS',
  [SP_COIN_DISPLAY.PENDING_SPONSOR_REWARDS]: 'PENDING_SPONSOR_REWARDS',
  [SP_COIN_DISPLAY.PENDING_RECIPIENT_REWARDS]: 'PENDING_RECIPIENT_REWARDS',
  [SP_COIN_DISPLAY.PENDING_AGENT_REWARDS]: 'PENDING_AGENT_REWARDS',
  [SP_COIN_DISPLAY.SPONSOR_ACCOUNT]: 'SPONSOR_ACCOUNT',
  [SP_COIN_DISPLAY.RECIPIENT_ACCOUNT]: 'RECIPIENT_ACCOUNT',
  [SP_COIN_DISPLAY.AGENT_ACCOUNT]: 'AGENT_ACCOUNT',
  [SP_COIN_DISPLAY.MANAGE_SPONSORSHIPS_PANEL]: 'MANAGE_SPONSORSHIPS_PANEL',
  [SP_COIN_DISPLAY.TOKEN_LIST_SELECT_PANEL]: 'TOKEN_LIST_SELECT_PANEL',
  [SP_COIN_DISPLAY.SELL_SELECT_PANEL]: 'SELL_SELECT_PANEL',
  [SP_COIN_DISPLAY.TOKEN_PANEL]: 'TOKEN_PANEL',
  [SP_COIN_DISPLAY.STAKING_SPCOINS_PANEL]: 'STAKING_SPCOINS_PANEL',
  [SP_COIN_DISPLAY.SWAP_ARROW_BUTTON]: 'SWAP_ARROW_BUTTON',
  [SP_COIN_DISPLAY.TRADE_CONTAINER_HEADER]: 'TRADE_CONTAINER_HEADER',
  [SP_COIN_DISPLAY.TRADING_STATION_PANEL]: 'TRADING_STATION_PANEL',
  [SP_COIN_DISPLAY.UNDEFINED]: 'UNDEFINED',
  [SP_COIN_DISPLAY.CHEVRON_DOWN_OPEN_PENDING]: 'CHEVRON_DOWN_OPEN_PENDING',
  [SP_COIN_DISPLAY.ACCOUNT_LIST_REWARDS_PANEL]: 'ACCOUNT_LIST_REWARDS_PANEL',
  [SP_COIN_DISPLAY.AGENT_LIST_SELECT_PANEL]: 'AGENT_LIST_SELECT_PANEL',
  [SP_COIN_DISPLAY.RECIPIENT_LIST_SELECT_PANEL]: 'RECIPIENT_LIST_SELECT_PANEL',
  [SP_COIN_DISPLAY.ACCOUNT_PANEL]: 'ACCOUNT_PANEL',
  [SP_COIN_DISPLAY.BUY_CONTRACT]: 'BUY_CONTRACT',
  [SP_COIN_DISPLAY.SELL_CONTRACT]: 'SELL_CONTRACT',
  [SP_COIN_DISPLAY.PREVIEW_CONTRACT]: 'PREVIEW_CONTRACT',
  [SP_COIN_DISPLAY.ACCOUNT_LIST_SELECT_PANEL]: 'ACCOUNT_LIST_SELECT_PANEL',
  [SP_COIN_DISPLAY.SPONSOR_LIST]: 'SPONSOR_LIST',
  [SP_COIN_DISPLAY.RECIPIENT_LIST]: 'RECIPIENT_LIST',
  [SP_COIN_DISPLAY.AGENT_LIST]: 'AGENT_LIST',
  [SP_COIN_DISPLAY.STAKE_TRADING_SPCOINS_PANEL]: 'STAKE_TRADING_SPCOINS_PANEL',
};
