import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from '../components/panes/footer'
import Header from '../components/panes/header'
import { ExchangeWrapper } from '../lib/context'
import ConnectWrapper2 from '../components/ConnectWrapper2'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
        {/* <ConnectWrapper2> */}

          {/* <ExchangeWrapper> */}
            <Header />
            {children}
            {/* <Footer /> */}
          {/* </ExchangeWrapper> */}
          {/* </ConnectWrapper2> */}
        </body>
      </html>
  )
}
