// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(menu)/(dynamic)/(accounts)/CreateAccount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/CreateAccount">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/(accounts)/CreateAccount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/(accounts)/CreateAgent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/CreateAgent">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/(accounts)/CreateAgent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/(accounts)/EditAccount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/EditAccount">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/(accounts)/EditAccount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/(accounts)/ManageAccounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ManageAccounts">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/(accounts)/ManageAccounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/RecipientSite/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/RecipientSite/help">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/RecipientSite/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/RecipientSite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/RecipientSite">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/RecipientSite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/SpCoinAPI/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/SpCoinAPI">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/SpCoinAPI/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/SpCoinAPI_OLD/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/SpCoinAPI_OLD">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/SpCoinAPI_OLD/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/SpCoinAccessController/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/SpCoinAccessController">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/SpCoinAccessController/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/SponsorCoinLab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/SponsorCoinLab">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/SponsorCoinLab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/(dynamic)/WhitePaper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/WhitePaper">> = Specific
  const handler = {} as typeof import("../../app/(menu)/(dynamic)/WhitePaper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/Exchange/DevTools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Exchange/DevTools">> = Specific
  const handler = {} as typeof import("../../app/(menu)/Exchange/DevTools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/Exchange/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Exchange">> = Specific
  const handler = {} as typeof import("../../app/(menu)/Exchange/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/SponsorCoin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/SponsorCoin">> = Specific
  const handler = {} as typeof import("../../app/(menu)/SponsorCoin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/Test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Test">> = Specific
  const handler = {} as typeof import("../../app/(menu)/Test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(menu)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/ethereum/price/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/ethereum/price">> = Specific
  const handler = {} as typeof import("../../app/api/0x/ethereum/price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/ethereum/quote/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/ethereum/quote">> = Specific
  const handler = {} as typeof import("../../app/api/0x/ethereum/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/polygon/balanceOf/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/polygon/balanceOf">> = Specific
  const handler = {} as typeof import("../../app/api/0x/polygon/balanceOf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/polygon/price/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/polygon/price">> = Specific
  const handler = {} as typeof import("../../app/api/0x/polygon/price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/polygon/quote/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/polygon/quote">> = Specific
  const handler = {} as typeof import("../../app/api/0x/polygon/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/price/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/price">> = Specific
  const handler = {} as typeof import("../../app/api/0x/price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/quote/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/quote">> = Specific
  const handler = {} as typeof import("../../app/api/0x/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/sepolia/price/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/sepolia/price">> = Specific
  const handler = {} as typeof import("../../app/api/0x/sepolia/price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/0x/sepolia/quote/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/0x/sepolia/quote">> = Specific
  const handler = {} as typeof import("../../app/api/0x/sepolia/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1Inch/quote/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1Inch/quote">> = Specific
  const handler = {} as typeof import("../../app/api/1Inch/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/alchemy/erc20/balanceOf/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alchemy/erc20/balanceOf">> = Specific
  const handler = {} as typeof import("../../app/api/alchemy/erc20/balanceOf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/native-token/[chainId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/native-token/[chainId]">> = Specific
  const handler = {} as typeof import("../../app/api/native-token/[chainId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/abi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/abi">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/abi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/access-manager/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/access-manager">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/access-manager/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/accounts/[accountAddress]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/accounts/[accountAddress]">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/accounts/[accountAddress]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/auth/nonce/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/auth/nonce">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/auth/nonce/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/auth/verify">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/contract-directories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/contract-directories">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/contract-directories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/contract-size-comparison/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/contract-size-comparison">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/contract-size-comparison/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/javascript-scripts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/javascript-scripts">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/javascript-scripts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/lab/account-popup-trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/lab/account-popup-trace">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/lab/account-popup-trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/lab/method-member-lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/lab/method-member-lists">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/lab/method-member-lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/lab/networks/[chainId]/testAccounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/lab/networks/[chainId]/testAccounts">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/lab/networks/[chainId]/testAccounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/run-script/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/run-script">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/run-script/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/scripts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/scripts">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/scripts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/tokens/[chainId]/[tokenAddress]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/tokens/[chainId]/[tokenAddress]">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/tokens/[chainId]/[tokenAddress]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spCoin/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spCoin/tokens">> = Specific
  const handler = {} as typeof import("../../app/api/spCoin/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/allowance/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/allowance">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/allowance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/balanceOf/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/balanceOf">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/balanceOf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/decimals/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/decimals">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/decimals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/name/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/name">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/name/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/symbol/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/symbol">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/symbol/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wagmi/erc20/totalSupply/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wagmi/erc20/totalSupply">> = Specific
  const handler = {} as typeof import("../../app/api/wagmi/erc20/totalSupply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(menu)/Test/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/Test">> = Specific
  const handler = {} as typeof import("../../app/(menu)/Test/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(menu)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(menu)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
