// File: lib/structure/exchangeContext/constants/spCoinDisplay.ts

import { SP_COIN_DISPLAY } from "../enums/spCoinDisplay";

export const MAIN_OVERLAY_GROUP: SP_COIN_DISPLAY[] = [
  SP_COIN_DISPLAY.TRADING_STATION_PANEL,
  SP_COIN_DISPLAY.SELL_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.BUY_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.RECIPIENT_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.AGENT_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.ERROR_MESSAGE_PANEL,
  SP_COIN_DISPLAY.SPONSOR_SELECT_PANEL_LIST,
];