// File: lib/structure/exchangeContext/constants/spCoinDisplay.ts
import { SP_COIN_DISPLAY } from "../enums/spCoinDisplay";

// ✅ MAIN_TRADING_PANEL is *not* part of the radio group
export const MAIN_OVERLAY_GROUP: SP_COIN_DISPLAY[] = [
  SP_COIN_DISPLAY.TRADING_STATION_PANEL,
  SP_COIN_DISPLAY.SELL_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.BUY_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.RECIPIENT_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.AGENT_SELECT_PANEL_LIST,
  SP_COIN_DISPLAY.ERROR_MESSAGE_PANEL,
  SP_COIN_DISPLAY.MANAGE_SPONSORSHIPS_PANEL, // ← add to radio group
  SP_COIN_DISPLAY.SPONSOR_SELECT_PANEL_LIST,  // legacy
];
