import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                {children}
            </body>
        </html>
    )
}
