// File: lib/structure/constants/enums/spCoinDisplay.ts
export enum SP_COIN_DISPLAY {
  TRADING_STATION_PANEL,
  SELL_SELECT_PANEL,
  SELL_SELECT_PANEL_LIST,
  BUY_SELECT_PANEL,
  BUY_SELECT_PANEL_LIST,
  RECIPIENT_SELECT_CONFIG_BUTTON,
  RECIPIENT_SELECT_PANEL,
  RECIPIENT_CONFIG_PANEL,
  RECIPIENT_SELECT_PANEL_LIST,
  SPONSORSHIP_SELECT_CONFIG_BUTTON,
  AGENT_SELECT_PANEL_LIST,
  ERROR_MESSAGE_PANEL,
  PRICE_BUTTON,
  SWAP_ARROW_BUTTON,
  FEE_DISCLOSURE,
  AFFILIATE_FEE,
  UNDEFINED,
  SPONSOR_SELECT_PANEL_LIST, // never persist

  // Append new members at the end to preserve prior numeric ids:
  SPONSOR_RATE_CONFIG_PANEL,
}
