import type { Metadata } from 'next'
// import Title from "./components/panes/title"

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <div>
            {children}
        </div>
    )
}
