import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from '../components/panes/footer'
import Header from '../components/panes/header'
import { ExchangeWrapper } from '../lib/context'
import SpCoinWrapper from '../components/SpCoinWrapper'
import { Web3Provider } from '../components/web3provider'
import { ConnectKitButton } from "connectkit";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/* <ExchangeWrapper> */}
      <SpCoinWrapper>
      {/* <Web3Provider> */}
        {/* <Header /> */}
        {children}
        {/* <ConnectKitButton /> */}
        {/* <Footer /> */}
      {/* </Web3Provider> */}
      </SpCoinWrapper>
      {/* </ExchangeWrapper> */}
    </>
  )
}
