import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from '@/components/panes/footer'
import Header from '@/components/panes/header'
import SpCoinWrapper from '@/components/SpCoinWrapper'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'spCoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/* <ExchangeWrapper> */}
      <SpCoinWrapper>
        <Header />
        {children}
        {/* <Footer /> */}
      </SpCoinWrapper>
    </>
  )
}
