// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/CreateAccount" | "/CreateAgent" | "/EditAccount" | "/Exchange" | "/Exchange/DevTools" | "/ManageAccounts" | "/RecipientSite" | "/RecipientSite/help" | "/SpCoinAPI" | "/SpCoinAccessController" | "/SponsorCoin" | "/SponsorCoinLab" | "/Test" | "/WhitePaper"
type AppRouteHandlerRoutes = "/api/0x/ethereum/price" | "/api/0x/ethereum/quote" | "/api/0x/polygon/balanceOf" | "/api/0x/polygon/price" | "/api/0x/polygon/quote" | "/api/0x/price" | "/api/0x/quote" | "/api/0x/sepolia/price" | "/api/0x/sepolia/quote" | "/api/1Inch/quote" | "/api/alchemy/erc20/balanceOf" | "/api/health" | "/api/native-token/[chainId]" | "/api/spCoin/abi" | "/api/spCoin/access-manager" | "/api/spCoin/accounts" | "/api/spCoin/accounts/[accountAddress]" | "/api/spCoin/auth/nonce" | "/api/spCoin/auth/verify" | "/api/spCoin/contract-directories" | "/api/spCoin/contract-size-comparison" | "/api/spCoin/javascript-scripts" | "/api/spCoin/lab/account-popup-trace" | "/api/spCoin/lab/method-member-lists" | "/api/spCoin/lab/networks/[chainId]/testAccounts" | "/api/spCoin/run-script" | "/api/spCoin/scripts" | "/api/spCoin/tokens" | "/api/spCoin/tokens/[chainId]/[tokenAddress]" | "/api/wagmi/erc20/allowance" | "/api/wagmi/erc20/balanceOf" | "/api/wagmi/erc20/decimals" | "/api/wagmi/erc20/name" | "/api/wagmi/erc20/symbol" | "/api/wagmi/erc20/totalSupply"
type PageRoutes = never
type LayoutRoutes = "/" | "/Test"
type RedirectRoutes = "/createRecipient" | "/websites/[site]"
type RewriteRoutes = "/assets/blockchains/31337/[[...path]]" | "/assets/blockchains/31337/info.json" | "/assets/blockchains/31337/logo.png" | "/editAccount"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/0x/ethereum/price": {}
  "/api/0x/ethereum/quote": {}
  "/api/0x/polygon/balanceOf": {}
  "/api/0x/polygon/price": {}
  "/api/0x/polygon/quote": {}
  "/api/0x/price": {}
  "/api/0x/quote": {}
  "/api/0x/sepolia/price": {}
  "/api/0x/sepolia/quote": {}
  "/api/1Inch/quote": {}
  "/api/alchemy/erc20/balanceOf": {}
  "/api/health": {}
  "/api/native-token/[chainId]": { "chainId": string; }
  "/api/spCoin/abi": {}
  "/api/spCoin/access-manager": {}
  "/api/spCoin/accounts": {}
  "/api/spCoin/accounts/[accountAddress]": { "accountAddress": string; }
  "/api/spCoin/auth/nonce": {}
  "/api/spCoin/auth/verify": {}
  "/api/spCoin/contract-directories": {}
  "/api/spCoin/contract-size-comparison": {}
  "/api/spCoin/javascript-scripts": {}
  "/api/spCoin/lab/account-popup-trace": {}
  "/api/spCoin/lab/method-member-lists": {}
  "/api/spCoin/lab/networks/[chainId]/testAccounts": { "chainId": string; }
  "/api/spCoin/run-script": {}
  "/api/spCoin/scripts": {}
  "/api/spCoin/tokens": {}
  "/api/spCoin/tokens/[chainId]/[tokenAddress]": { "chainId": string; "tokenAddress": string; }
  "/api/wagmi/erc20/allowance": {}
  "/api/wagmi/erc20/balanceOf": {}
  "/api/wagmi/erc20/decimals": {}
  "/api/wagmi/erc20/name": {}
  "/api/wagmi/erc20/symbol": {}
  "/api/wagmi/erc20/totalSupply": {}
  "/assets/blockchains/31337/[[...path]]": { "path"?: string[]; }
  "/assets/blockchains/31337/info.json": {}
  "/assets/blockchains/31337/logo.png": {}
  "/CreateAccount": {}
  "/CreateAgent": {}
  "/createRecipient": {}
  "/editAccount": {}
  "/EditAccount": {}
  "/Exchange": {}
  "/Exchange/DevTools": {}
  "/ManageAccounts": {}
  "/RecipientSite": {}
  "/RecipientSite/help": {}
  "/SpCoinAccessController": {}
  "/SpCoinAPI": {}
  "/SponsorCoin": {}
  "/SponsorCoinLab": {}
  "/Test": {}
  "/websites/[site]": { "site": string; }
  "/WhitePaper": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/Test": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
