export let rateInfo = "Sponsor Coin Staking rewards are generated contentiously calculated at a preset rate, currently 20%/annum.\n"
rateInfo += "The staking rewards may be claimed at any time and the proceeds are distributed according to the sponsor sharing proportions.\n"
rateInfo += "The staking rewards rate is set by the sponsor using the slide rule in this GUI.\n"
rateInfo += "If the purchaser does not sponsor a recipient to to share staking rewards then no staking rewards are generated.\n"
rateInfo += "Claiming the rewards is subject to network fees since the transactions are recorded on the block chain.\n"
rateInfo += "There are no SponsorCoin fees for SponsorCoin proof of stake claims.\n"
rateInfo += "No SponsorCoin rewards are allocated without a sponsor/recipient staking relationship."
rateInfo += "Network fees, although not substantial may be minimized through minimal staking reward claimed.\n"
rateInfo += "\n"
rateInfo += "Staking Rewards Calculation Formula:\n"
rateInfo += "====================================\n"
rateInfo += "Rewards = (amountStaked*annualRate) * (daysStaked/daysPerYear)\n"
rateInfo += "\n"
rateInfo += "Example:\n"
rateInfo += "amountStaked = 1000000 (SponsorCoin staking quantity)\n"
rateInfo += "annualRate 20% (A static interest rate system setting)\n"
rateInfo += "daysPerYear = 365.25. (Actual days in a solar years)\n"
rateInfo += "daysStaked = 30.524 days (Time since last staking request)\n"
rateInfo += "\n"
rateInfo += "The above example generates the following SponsorCoin Rewards:\n"
rateInfo += "\n"
rateInfo += "RewardCalculatedAmount = (1000000 * 0.20) * (30.524/365.25) = 16,714.03148528405\n"
rateInfo += "\n"
rateInfo += "These Rewards are distributed according to the staking rewards ratio.\n"
rateInfo += "\n"
rateInfo += "Sponsor/Recipient Rewards Distribution Formula:\n"
rateInfo += "===============================================\n"
rateInfo += "SponsorRewards = RewardCalculatedAmount * SponsorProportion\n"
rateInfo += "RecipientRewards = RewardCalculatedAmount * RecipientProportion\n"
rateInfo += "\n"
rateInfo += "For Example:\n"
rateInfo += "If the rewards sliding ratio ratio is set as follows:\n"
rateInfo += "SponsorRatio 40%\n"
rateInfo += "RecipientRatio 60%\n"
rateInfo += "Rewards will be distributed as follows:\n"
rateInfo += "\n"
rateInfo += "SponsorRewards = 16,714.03148528405 *0.4 = 6,685.612594113621.\n"
rateInfo += "RecipientRewards = 16,714.03148528405 *0.6 = 10,028.41889117043\n"
rateInfo += "\n"
rateInfo += "These amounts will be deposited to the associated Sponsor and Recipient wallet accounts accordingly.\n"
rateInfo += "These account deposits will not be sponsor staked.\n"